# Generated by Django 4.1.5 on 2023-01-03 23:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='polygon')),
            ],
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['title'], name='sites_title_idx'),
        ),
    ]
